/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package chatipv6;

import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import javax.swing.JFileChooser;
import javax.swing.JPanel;

/**
 *
 * @author miguelcardenas
 */
public class Ventana_cli extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_cli
     */
    public static Socket client;
    private Dispositivos miDispositivos;
    public int bandera;
    public Ventana_cli() {
        bandera=0;
        initComponents();
        miDispositivos = new Dispositivos(this); 
        client = null;
        selector = new JFileChooser();
        client = null;
        try {
            client = new Socket("fe80::61c0:7677:3729:7a6c", 5001);
            etiqueta_estado.setText("CONECTADO");
        } catch (IOException e) {
            System.out.println("Servidor no disponible");
            etiqueta_estado.setText("Servidor no Disponible");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        video = new javax.swing.JPanel();
        listuni = new javax.swing.JComboBox();
        unicast = new javax.swing.JButton();
        multicast = new javax.swing.JButton();
        pan_conversa = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        area_chat = new javax.swing.JTextArea();
        panel_mensaje = new javax.swing.JPanel();
        Field_mensaje = new javax.swing.JTextField();
        boton_enviar = new javax.swing.JButton();
        pan_archivos = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        campo_direccion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campo_dir_destino = new javax.swing.JTextField();
        pan_estado = new javax.swing.JPanel();
        combo_estado = new javax.swing.JComboBox();
        boton_estado = new javax.swing.JButton();
        etiqueta_titulo_estado = new javax.swing.JLabel();
        etiqueta_estado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        label_direccion = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campo_nick = new javax.swing.JTextField();
        etiqueta_nick = new javax.swing.JLabel();
        boton_nick = new javax.swing.JButton();
        jPwebcam = new javax.swing.JPanel();
        jPwebcam2 = new javax.swing.JPanel();
        encender = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        video.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        listuni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listuniActionPerformed(evt);
            }
        });

        unicast.setText("Unicast");

        multicast.setText("Multicast");

        org.jdesktop.layout.GroupLayout videoLayout = new org.jdesktop.layout.GroupLayout(video);
        video.setLayout(videoLayout);
        videoLayout.setHorizontalGroup(
            videoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(videoLayout.createSequentialGroup()
                .addContainerGap()
                .add(listuni, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 165, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(unicast)
                .addContainerGap(28, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, videoLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(multicast)
                .add(106, 106, 106))
        );
        videoLayout.setVerticalGroup(
            videoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(videoLayout.createSequentialGroup()
                .addContainerGap()
                .add(videoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(listuni, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(unicast))
                .add(18, 18, 18)
                .add(multicast)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pan_conversa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        area_chat.setColumns(20);
        area_chat.setRows(5);
        jScrollPane1.setViewportView(area_chat);

        org.jdesktop.layout.GroupLayout pan_conversaLayout = new org.jdesktop.layout.GroupLayout(pan_conversa);
        pan_conversa.setLayout(pan_conversaLayout);
        pan_conversaLayout.setHorizontalGroup(
            pan_conversaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pan_conversaLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1)
                .addContainerGap())
        );
        pan_conversaLayout.setVerticalGroup(
            pan_conversaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pan_conversaLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel_mensaje.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Field_mensaje.setText("Escribir Mensaje Aqui");
        Field_mensaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Field_mensajeMouseClicked(evt);
            }
        });
        Field_mensaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Field_mensajeKeyPressed(evt);
            }
        });

        boton_enviar.setText("ENVIAR");
        boton_enviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_enviarMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout panel_mensajeLayout = new org.jdesktop.layout.GroupLayout(panel_mensaje);
        panel_mensaje.setLayout(panel_mensajeLayout);
        panel_mensajeLayout.setHorizontalGroup(
            panel_mensajeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panel_mensajeLayout.createSequentialGroup()
                .addContainerGap()
                .add(Field_mensaje, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 432, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(boton_enviar)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panel_mensajeLayout.setVerticalGroup(
            panel_mensajeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, panel_mensajeLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .add(panel_mensajeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Field_mensaje, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(boton_enviar))
                .addContainerGap())
        );

        pan_archivos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setText("Dirección IPv6 Servidor:");

        campo_direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_direccionActionPerformed(evt);
            }
        });
        campo_direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campo_direccionKeyPressed(evt);
            }
        });

        jLabel2.setText("Direccion IPv6 Destino: ");

        campo_dir_destino.setText("::1");
        campo_dir_destino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_dir_destinoActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout pan_archivosLayout = new org.jdesktop.layout.GroupLayout(pan_archivos);
        pan_archivos.setLayout(pan_archivosLayout);
        pan_archivosLayout.setHorizontalGroup(
            pan_archivosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pan_archivosLayout.createSequentialGroup()
                .addContainerGap()
                .add(pan_archivosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel4)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pan_archivosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(campo_dir_destino, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .add(campo_direccion))
                .addContainerGap())
        );
        pan_archivosLayout.setVerticalGroup(
            pan_archivosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pan_archivosLayout.createSequentialGroup()
                .addContainerGap()
                .add(pan_archivosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(campo_direccion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(2, 2, 2)
                .add(pan_archivosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(campo_dir_destino, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pan_estado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        combo_estado.setEditable(true);
        combo_estado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Desconectado", "Conectado", "Ausente", "Ocupado" }));

        boton_estado.setText("Seleccionar");
        boton_estado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_estadoMouseClicked(evt);
            }
        });

        etiqueta_titulo_estado.setText("Estado: ");

        etiqueta_estado.setText("DESCONECTADO");

        jLabel1.setText("Direccion IPv6 Servidor:");

        label_direccion.setText("::1");

        jLabel3.setText("NICKNAME:");

        etiqueta_nick.setText("NICK");

        boton_nick.setText("Aceptar");
        boton_nick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_nickMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout pan_estadoLayout = new org.jdesktop.layout.GroupLayout(pan_estado);
        pan_estado.setLayout(pan_estadoLayout);
        pan_estadoLayout.setHorizontalGroup(
            pan_estadoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pan_estadoLayout.createSequentialGroup()
                .add(27, 27, 27)
                .add(pan_estadoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pan_estadoLayout.createSequentialGroup()
                        .add(combo_estado, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(boton_estado))
                    .add(pan_estadoLayout.createSequentialGroup()
                        .add(etiqueta_titulo_estado)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(etiqueta_estado))
                    .add(label_direccion)
                    .add(pan_estadoLayout.createSequentialGroup()
                        .add(jLabel3)
                        .add(18, 18, 18)
                        .add(etiqueta_nick))
                    .add(pan_estadoLayout.createSequentialGroup()
                        .add(pan_estadoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, campo_nick)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel1))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(boton_nick)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        pan_estadoLayout.setVerticalGroup(
            pan_estadoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pan_estadoLayout.createSequentialGroup()
                .addContainerGap()
                .add(pan_estadoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(combo_estado, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(boton_estado))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pan_estadoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(etiqueta_titulo_estado)
                    .add(etiqueta_estado))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(label_direccion)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(pan_estadoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(etiqueta_nick))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pan_estadoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(campo_nick, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(boton_nick))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPwebcam.setBorder(javax.swing.BorderFactory.createTitledBorder("TÚ"));

        org.jdesktop.layout.GroupLayout jPwebcamLayout = new org.jdesktop.layout.GroupLayout(jPwebcam);
        jPwebcam.setLayout(jPwebcamLayout);
        jPwebcamLayout.setHorizontalGroup(
            jPwebcamLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 301, Short.MAX_VALUE)
        );
        jPwebcamLayout.setVerticalGroup(
            jPwebcamLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 233, Short.MAX_VALUE)
        );

        jPwebcam2.setBorder(javax.swing.BorderFactory.createTitledBorder("CONTACTO"));

        org.jdesktop.layout.GroupLayout jPwebcam2Layout = new org.jdesktop.layout.GroupLayout(jPwebcam2);
        jPwebcam2.setLayout(jPwebcam2Layout);
        jPwebcam2Layout.setHorizontalGroup(
            jPwebcam2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );
        jPwebcam2Layout.setVerticalGroup(
            jPwebcam2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 0, Short.MAX_VALUE)
        );

        encender.setText("ON/OFF");
        encender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encenderActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        jLabel5.setText("Hangout UNET");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(layout.createSequentialGroup()
                                .add(jPwebcam2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(encender)
                                .add(73, 73, 73)
                                .add(jPwebcam, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, pan_conversa, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(panel_mensaje, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(video, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(pan_estado, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .add(14, 14, 14))
                    .add(layout.createSequentialGroup()
                        .add(pan_archivos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jLabel5)
                        .add(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, pan_archivos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel5))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jPwebcam, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jPwebcam2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .add(13, 13, 13)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(layout.createSequentialGroup()
                                .add(pan_conversa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(18, 18, 18)
                                .add(panel_mensaje, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(video, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(pan_estado, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(layout.createSequentialGroup()
                        .add(37, 37, 37)
                        .add(encender)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_nickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_nickMouseClicked
        // TODO add your handling code here:
        etiqueta_nick.setText(campo_nick.getText());
    }//GEN-LAST:event_boton_nickMouseClicked

    private void Field_mensajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Field_mensajeMouseClicked
        // TODO add your handling code here:
        Field_mensaje.setText(null);
    }//GEN-LAST:event_Field_mensajeMouseClicked

    private void Field_mensajeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Field_mensajeKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            if (client.isConnected()) {
                DataOutputStream salida;
                try {
                    salida = new DataOutputStream(client.getOutputStream());
                    salida.writeBytes(etiqueta_nick.getText() + ": " + Field_mensaje.getText() + "\n");
                } catch (IOException ex) {
                    System.out.println(ex.getMessage());
                }
            }
            Field_mensaje.setText(null);
        }
    }//GEN-LAST:event_Field_mensajeKeyPressed

    private void boton_enviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_enviarMouseClicked
        // TODO add your handling code here:
        if (client.isConnected()) {
            DataOutputStream salida;
            try {
                salida = new DataOutputStream(client.getOutputStream());
                salida.writeBytes(etiqueta_nick.getText() + ": " + Field_mensaje.getText() + "\n");
            } catch (IOException ex) {
                System.out.println(ex.getMessage());
            }
        }
        Field_mensaje.setText(null);
    }//GEN-LAST:event_boton_enviarMouseClicked

    private void boton_estadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_estadoMouseClicked
        // TODO add your handling code here:
        if (combo_estado.getSelectedIndex() == 0) {
            etiqueta_estado.setText("DESCONECTADO");
        } else if (combo_estado.getSelectedIndex() == 1) {
            etiqueta_estado.setText("Conectado");
        } else if (combo_estado.getSelectedIndex() == 2) {
            etiqueta_estado.setText("Ausente");
        } else if (combo_estado.getSelectedIndex() == 3) {
            etiqueta_estado.setText("Ocupado");
        }
    }//GEN-LAST:event_boton_estadoMouseClicked

    private void campo_direccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_direccionKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            label_direccion.setText(campo_direccion.getText());
            try {
                client = new Socket(label_direccion.getText(), 5001);
            } catch (IOException e) {
                System.out.println("Servidor no disponible");
            }
        }
    }//GEN-LAST:event_campo_direccionKeyPressed

    private void listuniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listuniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listuniActionPerformed

    private void campo_dir_destinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_dir_destinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_dir_destinoActionPerformed

    private void encenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encenderActionPerformed
        // TODO add your handling code here:
       bandera++;
        if (bandera==1) {
            miDispositivos.MuestraWebCam(jPwebcam,"vfw:Microsoft WDM Image Capture (Win32):0");
        } else if(bandera==2) {
            miDispositivos.getCerrarCam();
        }else{
            bandera=0;
        }
         
    }//GEN-LAST:event_encenderActionPerformed

    private void campo_direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_direccionActionPerformed
    /**
     * @param args the command line arguments
     */
    /* public static void main(String args[]) {
     /* Set the Nimbus look and feel 
     //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
     /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
     try {
     for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
     if ("Nimbus".equals(info.getName())) {
     javax.swing.UIManager.setLookAndFeel(info.getClassName());
     break;
     }
     }
     } catch (ClassNotFoundException ex) {
     java.util.logging.Logger.getLogger(Ventana_cli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     } catch (InstantiationException ex) {
     java.util.logging.Logger.getLogger(Ventana_cli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     } catch (IllegalAccessException ex) {
     java.util.logging.Logger.getLogger(Ventana_cli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     } catch (javax.swing.UnsupportedLookAndFeelException ex) {
     java.util.logging.Logger.getLogger(Ventana_cli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     }
     //</editor-fold>

     /* Create and display the form 
     java.awt.EventQueue.invokeLater(new Runnable() {
     public void run() {
     new Ventana_cli().setVisible(true);
     }
     });
     }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Field_mensaje;
    public javax.swing.JTextArea area_chat;
    private javax.swing.JButton boton_enviar;
    private javax.swing.JButton boton_estado;
    private javax.swing.JButton boton_nick;
    public javax.swing.JTextField campo_dir_destino;
    public javax.swing.JTextField campo_direccion;
    public javax.swing.JTextField campo_nick;
    private javax.swing.JComboBox combo_estado;
    private javax.swing.JToggleButton encender;
    public javax.swing.JLabel etiqueta_estado;
    public javax.swing.JLabel etiqueta_nick;
    private javax.swing.JLabel etiqueta_titulo_estado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPwebcam;
    private javax.swing.JPanel jPwebcam2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel label_direccion;
    public javax.swing.JComboBox listuni;
    public javax.swing.JButton multicast;
    private javax.swing.JPanel pan_archivos;
    private javax.swing.JPanel pan_conversa;
    private javax.swing.JPanel pan_estado;
    private javax.swing.JPanel panel_mensaje;
    public javax.swing.JButton unicast;
    private javax.swing.JPanel video;
    // End of variables declaration//GEN-END:variables

    public JPanel getjPwebcam() {
        return jPwebcam;
    }

    public void setjPwebcam(JPanel jPwebcam) {
        this.jPwebcam = jPwebcam;
    }
    public JFileChooser selector;
}
